/**
 * Standalone generation helpers (commit messages, session titles).
 *
 * ⚠️  DO NOT import from 'electron' or '../ipc' (mainSettings) here.
 * This file must stay free of Electron dependencies so it remains
 * unit-testable without an Electron runtime.
 */

import os from 'os'
import { gitService } from './git'
import { cleanCommitMessage, cleanSessionTitle } from './agentUtils'
import { getCliPath } from './claudePath'
import type { AgentSettings } from './agentTypes'

/** Extract text from SDK assistant messages. */
function extractText(q: AsyncIterable<Record<string, unknown>>): () => Promise<string> {
  return async () => {
    let result = ''
    for await (const message of q) {
      if (message.type === 'assistant' && 'message' in message) {
        const msg = message as Record<string, unknown>
        const content = msg.message as { content?: Array<{ type: string; text?: string }> }
        if (content?.content) {
          for (const block of content.content) {
            if (block.type === 'text' && block.text) {
              result += block.text
            }
          }
        }
      }
    }
    return result
  }
}

/** Snapshot and restore env vars around a callback. */
async function withEnvSnapshot<T>(
  settings: AgentSettings,
  fn: () => Promise<T>
): Promise<T> {
  const prevClaudeCode = process.env.CLAUDECODE
  const prevApiKey = process.env.ANTHROPIC_API_KEY
  try {
    delete process.env.CLAUDECODE
    if (settings.apiKey) {
      process.env.ANTHROPIC_API_KEY = settings.apiKey
    } else {
      delete process.env.ANTHROPIC_API_KEY
    }
    return await fn()
  } finally {
    if (prevClaudeCode !== undefined) process.env.CLAUDECODE = prevClaudeCode
    else delete process.env.CLAUDECODE
    if (prevApiKey !== undefined) process.env.ANTHROPIC_API_KEY = prevApiKey
    else delete process.env.ANTHROPIC_API_KEY
  }
}

async function importSdk() {
  try {
    const sdk = await import('@anthropic-ai/claude-agent-sdk')
    return sdk.query
  } catch (err) {
    throw new Error(`SDK import failed: ${err}`)
  }
}

export async function generateCommitMessage(
  worktreePath: string,
  settings: AgentSettings
): Promise<string> {
  const [diff, files] = await Promise.all([
    gitService.getStagedDiff(worktreePath),
    gitService.getStagedFiles(worktreePath)
  ])

  if (!diff.trim()) throw new Error('No staged changes')

  const queryFn = await importSdk()

  return withEnvSnapshot(settings, async () => {
    const MAX_DIFF_LENGTH = 30_000
    const truncatedDiff =
      diff.length > MAX_DIFF_LENGTH ? diff.slice(0, MAX_DIFF_LENGTH) + '\n\n[diff truncated]' : diff

    const prompt = `Staged files:\n${files.join('\n')}\n\nDiff:\n${truncatedDiff}`

    const abortController = new AbortController()
    const q = queryFn({
      prompt,
      options: {
        cwd: worktreePath,
        model: 'claude-haiku-4-5-20251001',
        maxTurns: 1,
        maxThinkingTokens: 0,
        persistSession: false,
        abortController,
        allowedTools: [],
        systemPrompt: `You are a commit message generator. Your ENTIRE response must be a valid git commit message — nothing else.

FORMAT:
type(scope): lowercase imperative description (max 72 chars)

Optional: blank line + 2-3 bullet points for complex changes.

RULES:
- Valid types: feat, fix, refactor, style, docs, test, chore, perf, ci, build
- Scope is optional — use only when it adds clarity
- No trailing period, no markdown fences, no explanations, no preamble
- Do NOT describe your thought process. Do NOT say what you're going to do. Just output the commit message.
- Do NOT add "Co-authored-by", "Generated by", or any AI/Claude attribution lines.
- If you output anything other than the commit message itself, you have failed your task.`,
        stderr: () => {},
        ...(getCliPath(settings.claudeCodeExecutablePath) ? { pathToClaudeCodeExecutable: getCliPath(settings.claudeCodeExecutablePath) } : {}),
      } as Parameters<typeof queryFn>[0]['options']
    })

    const result = await extractText(q as unknown as AsyncIterable<Record<string, unknown>>)()
    return cleanCommitMessage(result)
  })
}

export async function generateSessionTitle(
  userMessage: string,
  assistantSummary: string,
  settings: AgentSettings,
  currentTitle?: string
): Promise<string> {
  const queryFn = await importSdk()

  return withEnvSnapshot(settings, async () => {
    let prompt = `<task>TITLE_EXTRACTION</task>
<instructions>
Generate a concise tab title (3-7 words) for a coding agent session. The title should read like a PR title or Jira ticket — capturing the specific engineering task or goal, not describing the conversation.

Rules:
- Imperative mood, start with a verb (Add, Fix, Refactor, Implement, Update, Migrate, etc.)
- Be specific and technical — name the actual feature, component, file, or system
- Sentence case, no trailing punctuation, no quotes, no preamble
- Reply with ONLY the title

Good examples:
- Fix CORS headers in auth middleware
- Add dark mode toggle to settings
- Refactor payment service to async
- Implement WebSocket reconnection logic
- Update user search API pagination
- Migrate session store to IndexedDB

Bad examples (too vague):
- Help with code changes
- Fix a bug in the project
- Work on some improvements
- Update the application
- Discuss implementation approach
</instructions>
`
    if (currentTitle) {
      prompt += `<current_title>${currentTitle}</current_title>\n<evolve_hint>If the task scope has shifted, update the title to reflect the current focus. If still accurate, keep it.</evolve_hint>\n`
    }
    prompt += `<user_message>${userMessage}</user_message>\n<assistant_response>${assistantSummary}</assistant_response>\n<output>`

    const abortController = new AbortController()
    const q = queryFn({
      prompt,
      options: {
        cwd: os.tmpdir(),
        model: 'claude-haiku-4-5-20251001',
        maxTurns: 1,
        maxThinkingTokens: 0,
        persistSession: false,
        abortController,
        allowedTools: [],
        systemPrompt: `You are a structured data extractor. You receive tagged input and output ONLY the extracted value. Never converse, never explain, never greet. Output the raw value only.`,
        stderr: () => {},
        ...(getCliPath(settings.claudeCodeExecutablePath) ? { pathToClaudeCodeExecutable: getCliPath(settings.claudeCodeExecutablePath) } : {}),
      } as Parameters<typeof queryFn>[0]['options']
    })

    const result = await extractText(q as unknown as AsyncIterable<Record<string, unknown>>)()
    return cleanSessionTitle(result)
  })
}
