import { ThemePalette } from '../types'

export const arctic: ThemePalette = {
  id: 'arctic',
  name: 'Arctic',
  type: 'dark',
  source: 'builtin',
  group: 'dark',
  colors: {
    bgPrimary: '#2e3440',
    bgSecondary: '#3b4252',
    bgTertiary: '#434c5e',
    bgHover: '#4c566a',
    border: '#4c566a',
    textPrimary: '#eceff4',
    textSecondary: '#d8dee9',
    textMuted: '#7b88a1',
    accent: '#88c0d0',
    accentHover: '#8fbcbb',
    green: '#a3be8c',
    red: '#bf616a',
    amber: '#ebcb8b',
    olive: '#7b88a1',
    hlBase: '#d8dee9',
    hlComment: '#616e88',
    hlKeyword: '#81a1c1',
    hlAttrName: '#a3be8c',
    hlString: '#a3be8c',
    hlTitle: '#88c0d0',
    hlType: '#ebcb8b',
    hlNumber: '#b48ead',
    hlMeta: '#5e81ac',
    hlVariable: '#bf616a',
    hlTag: '#81a1c1',
    hlAttr: '#8fbcbb'
  },
  terminal: {
    black: '#3b4252',
    red: '#bf616a',
    green: '#a3be8c',
    yellow: '#ebcb8b',
    blue: '#81a1c1',
    magenta: '#b48ead',
    cyan: '#88c0d0',
    white: '#e5e9f0',
    brightBlack: '#4c566a',
    brightRed: '#d08770',
    brightGreen: '#a3be8c',
    brightYellow: '#ebcb8b',
    brightBlue: '#81a1c1',
    brightMagenta: '#b48ead',
    brightCyan: '#8fbcbb',
    brightWhite: '#eceff4'
  }
}
