import { ThemePalette } from '../types'

export const polar: ThemePalette = {
  id: 'polar',
  name: 'Polar',
  type: 'light',
  source: 'builtin',
  group: 'light',
  colors: {
    bgPrimary: '#eceff4',
    bgSecondary: '#e5e9f0',
    bgTertiary: '#d8dee9',
    bgHover: '#c8ced9',
    border: '#c0c8d6',
    textPrimary: '#2e3440',
    textSecondary: '#434c5e',
    textMuted: '#7b88a1',
    accent: '#5e81ac',
    accentHover: '#4c6e96',
    green: '#a3be8c',
    red: '#bf616a',
    amber: '#ebcb8b',
    olive: '#7b88a1',
    hlBase: '#2e3440',
    hlComment: '#7b88a1',
    hlKeyword: '#5e81ac',
    hlAttrName: '#a3be8c',
    hlString: '#a3be8c',
    hlTitle: '#88c0d0',
    hlType: '#d08770',
    hlNumber: '#b48ead',
    hlMeta: '#5e81ac',
    hlVariable: '#bf616a',
    hlTag: '#81a1c1',
    hlAttr: '#8fbcbb'
  },
  terminal: {
    black: '#2e3440',
    red: '#bf616a',
    green: '#a3be8c',
    yellow: '#ebcb8b',
    blue: '#5e81ac',
    magenta: '#b48ead',
    cyan: '#88c0d0',
    white: '#d8dee9',
    brightBlack: '#4c566a',
    brightRed: '#d08770',
    brightGreen: '#a3be8c',
    brightYellow: '#ebcb8b',
    brightBlue: '#81a1c1',
    brightMagenta: '#b48ead',
    brightCyan: '#8fbcbb',
    brightWhite: '#eceff4'
  }
}
